Initial version
lankastersky/zen-ios pull request #1
Opened 2018-07-11 01:21 UTC by lankastersky

Loading challenges from Firebase storage. UI shows a tab bar with 'Current challenge' tab and 'All challenges' tab

2018-07-11 11:39 UTC, NikAshanin requested changes

2018-07-11 11:39 UTC, NikAshanin commented on .gitignore
> +Podfile.lock
Ненадо podfile.lock в gitignore писать. Это специальный механизм для версионирования.

2018-07-11 11:39 UTC, NikAshanin commented on Podfile
> +# Uncomment the next line to define a global platform for your project
Лишнее всё удаляй сразу)

2018-07-11 11:39 UTC, NikAshanin commented on Podfile
> +# platform :ios, '9.0'
раскомменть

2018-07-11 11:39 UTC, NikAshanin commented on Podfile
> +  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
удали лишние строки

2018-07-11 11:39 UTC, NikAshanin commented on Podfile
> +  target 'zenTests' do
удаляй тесты) если не юзаешь)

2018-07-11 11:39 UTC, NikAshanin commented on Podfile
> +  target 'zenUITests' do
удаляй тесты) если не юзаешь)

2018-07-11 11:39 UTC, NikAshanin commented on zen.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
в гитигнор это)

2018-07-11 11:39 UTC, NikAshanin commented on zen.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
в гитигнор

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +                print("Failed to authenticate in Firebase: \(error)")
А если ошибка - то приложение просто ничего не показывает?

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +                        self.updateChallengeViewController(challenges!)
тут [weak self]

И убирай force unwrap везде. Подключи для этого swiftlint

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +        let tabBarController = self.window!.rootViewController as! UITabBarController
Это нужно убрать отсюда в какой-нибудь либо extension либо в другой класс роутинга

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +        let tabBarController = self.window!.rootViewController as! UITabBarController
self лишний + 2 force unwrap убирай

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +        let challengeNavigationController: UINavigationController =
tabBarController.viewControllers![0] -> tabBarController.viewControllers.first

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +            tabBarController.viewControllers![0] as! UINavigationController
let challengeNavigationController: (UINavigationController  тут не нужен, ты и так к нему кастишь)

2018-07-11 11:39 UTC, NikAshanin commented on zen/AppDelegate.swift
> +        let challengeViewController: ChallengeViewController =
тоже самое

2018-07-11 11:39 UTC, NikAshanin commented on zen/Info.plist
> +		<string>UIInterfaceOrientationLandscapeLeft</string>
действительно работает во всех ориентациях?

2018-07-11 11:39 UTC, NikAshanin commented on zen/Info.plist
> +		<string>UIInterfaceOrientationPortrait</string>
и есть поддержка ipad?

2018-07-11 11:39 UTC, NikAshanin commented on zen/models/Challenge.swift
> +/// Challenge model
Это из названия понятно, зачем коммент?

2018-07-11 11:39 UTC, NikAshanin commented on zen/models/Challenge.swift
> +struct Challenge: Decodable {
почему структура, а не класс?

2018-07-11 11:39 UTC, NikAshanin commented on zen/models/Challenge.swift
> +import Foundation
Зачем этот импорт?

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +class ChallengesProvider {
final class

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private static let CHALLENGES_FILE_NAME: String = "challenges"
Обычное название без больших букв подойдет.

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private static let CHALLENGES_FILE_NAME: String = "challenges"
и :String не нужно писать, компилятор сам поймет, что это строка из-за присвоения

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    static let shared = ChallengesProvider()
все синглтоны удаляй :)

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private var _challenges: [String: Challenge] = [:]
что за нижнее подчеркивание?) Это не obj-c))

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private init() {
пустой метод удаляй) нет тут синглтона)

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +            return _challenges
это не obj-c)) удаляй

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let constants = NSDictionary(contentsOfFile: path)!
force unwrap удаляй

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let path = Bundle.main.path(forResource: "Config", ofType: "plist")!
force unwrap удаляй

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let email = constants["email"] as! String
force unwrap удаляй и зачем хранить пароль в plist? это несекьюрно, даже в коде лучше.

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let password = constants["password"] as! String
тоже самое

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        if user == nil {
if user {
}

а лучше guard юзай тут

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private class func zippedChallengesFilePath(_ filename: String) -> URL {
static func

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let documentsDirectory = paths[0]
.first

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        return URL(string: filePath)!
force unwrap удаляй

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private class func zippedChallengesFilePath(_ filename: String) -> URL {
лучше это в extension засовывать

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        return try Data(contentsOf: unzipURL!)
force unwrap remove

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private class func unzip(_ sourcePath: URL, _ fileName: String) throws -> Data {
static func + в extension его

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +                        .unzip(url!, "\(ChallengesProvider.CHALLENGES_FILE_NAME).json")
что за json? зачем?

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        fileRef.write(toFile: localURL) { url, error in
зачем писать в файл? что тут происходит?)

2018-07-11 11:39 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        // There is no easy way to decompress zip data directly to memory. So storing it as a
ты уверен?) А если поискать?)

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +class ChallengeViewController: UIViewController {
final class

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +/// Shows current challenge
Просто название более говорящее и не нужны такие комментарии "ChallengeDetailViewController

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var content: UILabel!
private

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var details: UILabel!
private

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var content: UILabel!
contentLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var details: UILabel!
detailsLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var quote: UILabel!
private quoteLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var source: UILabel!
private sourceLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var type: UILabel!
private typeLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var url: UILabel!
private urlLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        self.navigationItem.title = "Current Challenge"
self redandunt

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        let challenge = Array(challenges.values)[challengeIndex]
упадет тут, что это вообще?)

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        let challenges = ChallengesProvider.shared.challenges
не нужен тут синглтон

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        let challengeIndex = 0
оО

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalCollectionViewCell.swift
> +//
давай удалим все комментарии верхние, зачем они, только количество строчек добавляют

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalCollectionViewCell.swift
> +class JournalCollectionViewCell: UICollectionViewCell {
final class

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalCollectionViewCell.swift
> +    @IBOutlet var content: UILabel!
тоже везде private и тоже везде label суффикс, contentLabel

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +class JournalViewController: UICollectionViewController {
final class

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +class JournalViewController: UICollectionViewController {
делай обычный UIViewController, c добавленным UICollectionView

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +/// Shows the Journal of finished challenges
тоже самое

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        self.navigationItem.title = "Finished Challenges"
self лишний

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    private static let JOURNAL_VIEW_CELL_REUSE_IDENTIFIER = "JournalViewCell"
опять obj-c название константы

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    private static let JOURNAL_VIEW_CELL_REUSE_IDENTIFIER = "JournalViewCell"
И эту константу нужно выносить в ячейку, а не в контроллер

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    // MARK: UICollectionViewDataSource
в extension это разнеси

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    override func numberOfSections(in collectionView: UICollectionView) -> Int {
если 1 то можно вообще не писать этот метод, по дефолту 1

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        let challenge: Challenge = Array(challenges.values)[indexPath.item]
упадет тут

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        // Configure the cell
коммент без смысла

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +            for: indexPath) as! JournalCollectionViewCell
force unwrap

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        cell.backgroundColor = self.randomColor()
self не нужен

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    func randomColor() -> UIColor{
в extension в виде init для UIColor

2018-07-11 11:39 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    // MARK: UICollectionViewDelegate
весь закоменченный код удаляй

2018-07-11 11:39 UTC, NikAshanin commented on zenTests/zenTests.swift
> +class zenTests: XCTestCase {
удаляй все пустые тесты, вместе с ненужными тестовыми таргетами

2018-07-11 11:39 UTC, NikAshanin commented on zenUITests/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
удаляй тесты пустые)

2018-07-11 11:39 UTC, NikAshanin commented on zenUITests/zenUITests.swift
> +class zenUITests: XCTestCase {
пустые тесты удаляй)

2018-07-11 16:56 UTC, lankastersky commented on .gitignore
> +Podfile.lock
done

2018-07-11 16:56 UTC, lankastersky commented on Podfile
> +# Uncomment the next line to define a global platform for your project
done

2018-07-11 16:57 UTC, lankastersky commented on Podfile
> +# platform :ios, '9.0'
done

2018-07-11 16:57 UTC, lankastersky commented on Podfile
> +  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
done

2018-07-11 16:57 UTC, lankastersky commented on Podfile
> +  target 'zenTests' do
потом буду юзать

2018-07-11 16:58 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    func randomColor() -> UIColor{
это временно, добавил TODO: remove

2018-07-11 16:59 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    // MARK: UICollectionViewDelegate
я его буду юзать скоро, добавил TODO

2018-07-11 17:01 UTC, lankastersky commented on zenTests/zenTests.swift
> +class zenTests: XCTestCase {
добавил TODO: implement

2018-07-12 11:43 UTC, NikAshanin requested changes

2018-07-12 11:43 UTC, NikAshanin commented on zen.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
В gitignore, ненадо комитить файлы из xcshareddata

2018-07-12 11:43 UTC, NikAshanin commented on zen.xcworkspace/contents.xcworkspacedata
> +<?xml version="1.0" encoding="UTF-8"?>
xcworkspace тоже в гитигнор

2018-07-12 11:43 UTC, NikAshanin commented on zen.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
!!!)))

2018-07-12 11:43 UTC, NikAshanin commented on zen/AppDelegate.swift
> +//
комментарий удали плз

2018-07-12 11:43 UTC, NikAshanin commented on zen/AppDelegate.swift
> +    var challengesProvider = ChallengesProvider()
зачем его создавать на старте приложения? получается сервис локатор, который еще и вызывает лаги на старте. создавай там, где реально нужен он, либо через lazy var

2018-07-12 11:43 UTC, NikAshanin commented on zen/AppDelegate.swift
> +    var challengesProvider = ChallengesProvider()
я за первый вариант

2018-07-12 11:43 UTC, NikAshanin commented on zen/Info.plist
> +	<key>UISupportedInterfaceOrientations~ipad</key>
ipad поддержка есть? удалить мб?

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        if user == nil {
if user {
}
== nil не нужен

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +                        .unzip(url!, "\(ChallengesProvider.challengesFileName).json")
unwrap remove

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let fileRef = self.storage.reference().child(zipFileName)
self weak

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        // There is no easy way to decompress zip data directly to memory. So storing it as a
??? точно нет способа? как то не верится

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private class func unzip(_ sourcePath: URL, _ fileName: String) throws -> Data {
static

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private class func parseChallenges(data: Data?) throws -> [String: Challenge] {
static

2018-07-12 11:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +    private class func zippedChallengesFilePath(_ filename: String) -> URL? {
static

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
вот так точно ненадо. почему просто тут не создать этот сервис и дальше его передавать? зачем нужен тут этот синглтон

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        let challengesProvider = appDelegate.challengesProvider
тут вот и создай просто

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +                        self.challenges = challenges
weak self

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +                        self.showCurrentChallenge()
weak self

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        // TODO: choose proper index
wtf?))) объясни что это

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalCollectionViewCell.swift
> +    @IBOutlet weak var widthConstraint: NSLayoutConstraint!
private

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalCollectionViewCell.swift
> +        widthConstraint.constant = screenWidth - 2 * 12
оО? А само не растянется?

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    private static let journalViewCellReuseIdentifier = "JournalViewCell"
идентификатор ячейки в саму ячейку же. почему контроллер знает идентификатор какой-то ячейки? SOLID же

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
опять оно, я выше отписал что с этим делать)

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        collectionView?.register(UINib.init(nibName: "JournalCollectionViewCell", bundle: nil),
.init можно не писать в свифте

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        if let flowLayout = collectionView?.collectionViewLayout as? UICollectionViewFlowLayout {
оО? что это

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    // MARK: UICollectionViewDataSource
в extension вынести

2018-07-12 11:43 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +    func randomColor() -> UIColor {
в extension вынести

2018-07-12 16:06 UTC, lankastersky commented on zen.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
done

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +                print("Failed to authenticate in Firebase: \(error)")
done

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +                        self.updateChallengeViewController(challenges!)
done

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +        let tabBarController = self.window!.rootViewController as! UITabBarController
moved to another controller

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +        let tabBarController = self.window!.rootViewController as! UITabBarController
done

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +        let challengeNavigationController: UINavigationController =
done

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +            tabBarController.viewControllers![0] as! UINavigationController
done

2018-07-12 16:06 UTC, lankastersky commented on zen/AppDelegate.swift
> +        let challengeViewController: ChallengeViewController =
done

2018-07-12 16:06 UTC, lankastersky commented on zen/Info.plist
> +		<string>UIInterfaceOrientationLandscapeLeft</string>
должно будет, вместо ui пока заглушки

2018-07-12 16:06 UTC, lankastersky commented on zen/Info.plist
> +		<string>UIInterfaceOrientationPortrait</string>
removed

2018-07-12 16:06 UTC, lankastersky commented on zen/models/Challenge.swift
> +import Foundation
removed

2018-07-12 16:06 UTC, lankastersky commented on zen/models/Challenge.swift
> +/// Challenge model
для единообразия - ко всем классам коменты

2018-07-12 16:06 UTC, lankastersky commented on zen/models/Challenge.swift
> +struct Challenge: Decodable {
для простоты

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +class ChallengesProvider {
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    private static let CHALLENGES_FILE_NAME: String = "challenges"
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    static let shared = ChallengesProvider()
а куда его сохранить?

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    private var _challenges: [String: Challenge] = [:]
есть такое же публичное проперти, чтобы отличать имена

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        let path = Bundle.main.path(forResource: "Config", ofType: "plist")!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        let constants = NSDictionary(contentsOfFile: path)!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        let email = constants["email"] as! String
done. я не кладу plist в github

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        let password = constants["password"] as! String
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        if user == nil {
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        // There is no easy way to decompress zip data directly to memory. So storing it as a
искал, не нашел

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        fileRef.write(toFile: localURL) { url, error in
выше коммент см:
        // There is no easy way to decompress zip data directly to memory. So storing it as a
        // temporary file, unzip to another file and read to NSData.

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    private class func unzip(_ sourcePath: URL, _ fileName: String) throws -> Data {
сделано class чтобы в тестах можно было переопределить если что.
А почему тут extention лучше?

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        return try Data(contentsOf: unzipURL!)
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        let documentsDirectory = paths[0]
done

2018-07-12 16:06 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        return URL(string: filePath)!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +class ChallengeViewController: UIViewController {
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var content: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var content: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var details: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var details: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var quote: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var source: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var type: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +    @IBOutlet weak var url: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        self.navigationItem.title = "Current Challenge"
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        let challengeIndex = 0
TODO added

2018-07-12 16:06 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        let challenge = Array(challenges.values)[challengeIndex]
TODO added

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalCollectionViewCell.swift
> +class JournalCollectionViewCell: UICollectionViewCell {
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalCollectionViewCell.swift
> +//
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalCollectionViewCell.swift
> +    @IBOutlet var content: UILabel!
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +class JournalViewController: UICollectionViewController {
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +class JournalViewController: UICollectionViewController {
а в чем разница? я его дальше буду дорабатывать

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    private static let JOURNAL_VIEW_CELL_REUSE_IDENTIFIER = "JournalViewCell"
renamed

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    private static let JOURNAL_VIEW_CELL_REUSE_IDENTIFIER = "JournalViewCell"
зачем? тут она private

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        self.navigationItem.title = "Finished Challenges"
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    override func numberOfSections(in collectionView: UICollectionView) -> Int {
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +            for: indexPath) as! JournalCollectionViewCell
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        // Configure the cell
done

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        let challenge: Challenge = Array(challenges.values)[indexPath.item]
почему? я ж знаю challenges.count

2018-07-12 16:06 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        cell.backgroundColor = self.randomColor()
done

2018-07-12 16:06 UTC, lankastersky commented on zenUITests/zenUITests.swift
> +class zenUITests: XCTestCase {
done

2018-07-12 16:06 UTC, lankastersky commented on zenUITests/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
done

2018-07-12 16:06 UTC, lankastersky commented on Podfile
> +  target 'zenUITests' do
done

2018-07-12 16:06 UTC, lankastersky commented on Podfile
> +  target 'zenTests' do
done

2018-07-14 00:27 UTC, lankastersky commented on zen.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
решили оставить

2018-07-14 00:27 UTC, lankastersky commented on zen/Info.plist
> +	<key>UISupportedInterfaceOrientations~ipad</key>
done

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        // There is no easy way to decompress zip data directly to memory. So storing it as a
скажу спасибо если найдешь

2018-07-14 00:27 UTC, lankastersky commented on zen.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
решили оставить

2018-07-14 00:27 UTC, lankastersky commented on zen/AppDelegate.swift
> +//
done

2018-07-14 00:27 UTC, lankastersky commented on zen/AppDelegate.swift
> +    var challengesProvider = ChallengesProvider()
made lazy

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        if user == nil {
Optional type 'User?' cannot be used as a boolean; test for '!= nil' instead

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +        let fileRef = self.storage.reference().child(zipFileName)
done

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +                        .unzip(url!, "\(ChallengesProvider.challengesFileName).json")
done

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    private class func unzip(_ sourcePath: URL, _ fileName: String) throws -> Data {
done

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    private class func parseChallenges(data: Data?) throws -> [String: Challenge] {
done

2018-07-14 00:27 UTC, lankastersky commented on zen/services/ChallengesProvider.swift
> +    private class func zippedChallengesFilePath(_ filename: String) -> URL? {
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
решили оставить

2018-07-14 00:27 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        let challengesProvider = appDelegate.challengesProvider
решили оставить

2018-07-14 00:27 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +                        self.challenges = challenges
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +                        self.showCurrentChallenge()
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        // TODO: choose proper index
бизнес-логика будет реализована позже, это заглушка

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalCollectionViewCell.swift
> +    @IBOutlet weak var widthConstraint: NSLayoutConstraint!
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalCollectionViewCell.swift
> +        widthConstraint.constant = screenWidth - 2 * 12
Нет. Добавил TODO

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    private static let journalViewCellReuseIdentifier = "JournalViewCell"
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
решили оставить

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        collectionView?.register(UINib.init(nibName: "JournalCollectionViewCell", bundle: nil),
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        if let flowLayout = collectionView?.collectionViewLayout as? UICollectionViewFlowLayout {
добавил коммент

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    // MARK: UICollectionViewDataSource
done

2018-07-14 00:27 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +    func randomColor() -> UIColor {
added TODO: remove after implementing real cells

2018-07-14 10:43 UTC, NikAshanin approved these changes

2018-07-14 10:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        let fileRef = self.storage.reference().child(zipFileName)
self redundant

2018-07-14 10:43 UTC, NikAshanin commented on zen/services/ChallengesProvider.swift
> +        return try Data(contentsOf: unzipURL!)
force unwrap

2018-07-14 10:43 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        challengesProvider?.signIn(callback: {[weak self] _, error in
вынеси в отдельный метод

2018-07-15 02:54 UTC, merged