Challenges workflow and business logic implementation
lankastersky/zen-ios pull request #2
Opened 2018-07-15 04:45 UTC by lankastersky

2018-07-16 15:27 UTC, NikAshanin requested changes

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +    mutating func updateStatus() {
делай класс, никаких mutation func

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +    mutating func decline() {
тоже самое

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +    mutating func reset() {
тоже самое

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +        default:
вроде можно без default

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +        default:
вроде можно без default

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +            print("Challenge id is not defined")
может быть такое, что нет ID? я бы сделал падение в этом месте

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/Challenge.swift
> +            challengeId = ""
нене, вот это что-то выглядит плохо

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengeData.swift
> +struct ChallengeData {
никаких структур. структуры в swift используй только как это делает apple (CGPoint, CGRect и тд)

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private var currentChallengeId = ""
wtf?)

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private var challengesMap: [String: Challenge] = [:]
что за MAP? Dictionary это, нет MAP в swift

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private(set) var currentLevel: ChallengeLevel = ChallengeLevel.low
private(set) var currentLevel: ChallengeLevel = .low

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        get { return challengesMap[currentChallengeId] }
возможно падение же. небезопасный код

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +            let shownNumber: Int = challengesByStatus(ChallengeStatus.shown).count
Int зачем писать это? count вернет только инт)

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +            return challenges.sorted(by: { (left, right) -> Bool in
return challenges.sorted(by: { $0. challengeId < $1. challengeId })

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        return finishedChallenges.sorted(by: { (left, right) -> Bool in
тоже самое

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        return finishedChallenges.sorted(by: { (left, right) -> Bool in
тоже самое

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        self.challengesMap = challengesMap
self redundant...

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +                    challengesMap[challenge.challengeId] = challenge
тут падение

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if challengesMap.isEmpty {
слишком высокая цикломатическая сложность. юзай гварды

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +                for challenge in challenges {
challenges.forEach

старайся юзать функциональный подход вообще

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        challengesArchiver.storeChallengeData(challengesMap)
нельзя это всё вынести в challengesArchiver?

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if currentChallengeId == "" {
и тут я долго пытался выразиться культурно :) В общем, ненадо так :)

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        var newChallengeRequired = false
тут явно без этого можно красиво сделать, давай подумаем как это сделать красиво

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private func newChallengeId() -> String {
private var

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if !(filteredNonFinishedChallenges.isEmpty) {
минутка иронии: если цикломатическая сложность метода ниже 10, то он просто не пройдет ревью в гугл? :)
Давай упростим метод и разнесем в разные или как-то еще. условие, внутри условие, внутри условие и там еще цикл - это больно

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if challenges.isEmpty {
guard

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private class func randomChallenge(_ challenges: [Challenge]) -> Challenge {
static

2018-07-16 15:27 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        for challenge in challengesMap.values where challenge.status == challengeStatus {
try to use .filter
MORE functional style plz

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +    mutating func updateStatus() {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +        default:
мне нужна защита против обработки оставшихся статусов

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +    mutating func decline() {
мне нужна защита против обработки оставшихся статусов

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +        default:
мне нужна защита против обработки оставшихся статусов

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +    mutating func reset() {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +            print("Challenge id is not defined")
сделал падение

2018-07-16 22:13 UTC, lankastersky commented on zen/models/Challenge.swift
> +            challengeId = ""
согласен

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengeData.swift
> +struct ChallengeData {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +    private var challengesMap: [String: Challenge] = [:]
хаха да) но мне так привычней

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +    private var currentChallengeId = ""
он исползуется как ключ в словаре

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +    private(set) var currentLevel: ChallengeLevel = ChallengeLevel.low
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        get { return challengesMap[currentChallengeId] }
почему падение? опциональный тип возвращается

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +            let shownNumber: Int = challengesByStatus(ChallengeStatus.shown).count
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +            return challenges.sorted(by: { (left, right) -> Bool in
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        return finishedChallenges.sorted(by: { (left, right) -> Bool in
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        self.challengesMap = challengesMap
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        if challengesMap.isEmpty {
пробовал, пишет
'guard' body must not fall through, consider using a 'return' or 'throw' to exit the scope

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +                for challenge in challenges {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +                    challengesMap[challenge.challengeId] = challenge
можешь пояснить?

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        challengesArchiver.storeChallengeData(challengesMap)
наружу торчит только модель, она фасад

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        var newChallengeRequired = false
я уже думал)

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        if currentChallengeId == "" {
а как?

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +    private func newChallengeId() -> String {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        if challenges.isEmpty {
как?

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        for challenge in challengesMap.values where challenge.status == challengeStatus {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +    private class func randomChallenge(_ challenges: [Challenge]) -> Challenge {
done

2018-07-16 22:13 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        if !(filteredNonFinishedChallenges.isEmpty) {
хаха ты прав) вот что бывает когда пишешь код по ночам) уменьшил сложность

2018-07-17 11:48 UTC, NikAshanin requested changes

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
>  /// Challenge model
Вот с именованием бы поработать прям. Я хз откуда это всё взято))
Тут в комментарии написано /// Challenge model
При этом есть отдельно ChallengesModel
Ну и тд. Сделай нормальную конвенцию, типо сервис для бизнес логики, модель - это реально модель, ну и тд. Сейчас всякие провайдеры и тд - что это вообще

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
> +    let prevRatings: [Float]? = nil
оно и так nil, если ? ставишь
лишний код просто, удаляй

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
> +    let prevFinishedTimes: [TimeInterval]? = nil
оно и так nil, если ? ставишь
лишний код просто, удаляй

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
> +    let prevStatuses: [Int]? = nil
оно и так nil, если ? ставишь
лишний код просто, удаляй

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
> +        default:
лучше так и напиши, что такие статусы неприемлимы. Просто если default не будет, а ты расширишь этот enum, то сразу увидишь где нужно что добавить. С default так не сработает и будут ошибки, которые нужно руками искать

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
> +        default:
лучше так и напиши, что такие статусы неприемлимы. Просто если default не будет, а ты расширишь этот enum, то сразу увидишь где нужно что добавить. С default так не сработает и будут ошибки, которые нужно руками искать

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/Challenge.swift
> +            level = .low
wtf?) как это и зачем?)

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengeData.swift
> +final class ChallengeData {
еще и Data суффикс. конценцию наименований я бы ввел все-таки и отписал сюда, что и как ты называешь. сейчас просто солянка супчик

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private var challengesMap: [String: Challenge] = [:]
Тебе то да, но ты пишешь в том числе не для себя. И надо следовать стандартам, которые приняты в языке, который ты используешь, чтобы было понятно ДРУГИМ людям :)

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +    private var currentChallengeId = ""
пустой строкой быть не может

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if challengesMap.isEmpty {
а что не так? внутри должен быть return

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +                    challengesMap[challenge.challengeId] = challenge
тут упадет

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if currentChallengeId == "" {
ну не может быть логически ID чего-то пустой строкой
тогда уж nil

2018-07-17 11:48 UTC, NikAshanin commented on zen/models/ChallengesModel.swift
> +        if challenges.isEmpty {
guard !challenges.isEmpty else { return [] }

2018-07-17 11:48 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        if let challenge = challengesModel?.sortedChallenges[challengeIndex] {
упадет тут

2018-07-17 11:48 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        let challenge: Challenge = challenges[indexPath.item]
упадет тут

2018-07-17 18:03 UTC, lankastersky commented on zen/models/Challenge.swift
> +        default:
done

2018-07-17 18:03 UTC, lankastersky commented on zen/models/Challenge.swift
> +        default:
done

2018-07-17 18:06 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +        if challenges.isEmpty {
done

2018-07-17 18:07 UTC, lankastersky commented on zen/models/Challenge.swift
>  /// Challenge model
есть предложения?

2018-07-17 18:07 UTC, lankastersky commented on zen/models/Challenge.swift
> +    let prevRatings: [Float]? = nil
done

2018-07-17 18:08 UTC, lankastersky commented on zen/models/Challenge.swift
> +    let prevFinishedTimes: [TimeInterval]? = nil
done

2018-07-17 18:08 UTC, lankastersky commented on zen/models/Challenge.swift
> +    let prevStatuses: [Int]? = nil
done

2018-07-17 18:09 UTC, lankastersky commented on zen/models/ChallengesModel.swift
> +                    challengesMap[challenge.challengeId] = challenge
почему?

2018-07-17 18:10 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        if let challenge = challengesModel?.sortedChallenges[challengeIndex] {
// TODO: choose proper index

2018-07-17 18:11 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        let challenge: Challenge = challenges[indexPath.item]
почему? я ж знаю сколько там элементов и возвращаю это при создании листа

2018-07-17 18:35 UTC, lankastersky commented on zen/models/Challenge.swift
> +            level = .low
что именно? если ты прод кастомный конструктор, то дефолтный не подходит потому что мне не все поля надо декодировать

2018-07-17 18:35 UTC, lankastersky commented on zen/models/ChallengeData.swift
> +final class ChallengeData {
renamed to MutableChallengeData

2018-07-18 09:42 UTC, NikAshanin requested changes

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/Challenge.swift
> +            level = .low
почему если не распрарсило, то ты делаешь .low?

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/ChallengesManager.swift
> +    private var challengesMap: [String: Challenge] = [:]
Map переименуй, пожалуйста) Код пишем для других людей все-таки, согласно общепринятым языковым конвенциям

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/ChallengesManager.swift
> +                return challengesMap[currentChallengeId]
упадет тут. Обращение может произойти по ключу, которого нет в словаре

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/ChallengesManager.swift
> +        return challengesMap[challengeId]
упадет тут. Обращение может произойти по ключу, которого нет в словаре

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/ChallengesManager.swift
> +        if currentChallengeId == "" {
нельзя сравнивать с пустой строкой. Вообще id не может быть пустой строкой. либо nil, либо значение нормальное. это только запутывает

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/ChallengesManager.swift
> +            if !(filteredNonFinishedChallenges.isEmpty) {
guard здесь лучше

2018-07-18 09:42 UTC, NikAshanin commented on zen/models/ChallengesManager.swift
> +            if !declinedChallenges.isEmpty
guard здесь лучше

2018-07-18 09:42 UTC, NikAshanin commented on zen/views/JournalViewController.swift
> +        let challenge: Challenge = challenges[indexPath.item]
считается небезопасным кодом. пример: приходит другой разраб и добавляет еще одну ячейку как хедер и всё падает

2018-07-18 20:41 UTC, NikAshanin approved these changes

2018-07-18 22:02 UTC, lankastersky commented on zen/models/Challenge.swift
> +            level = .low
согласен, поменял на эксепшн

2018-07-18 22:02 UTC, lankastersky commented on zen/models/ChallengesManager.swift
> +    private var challengesMap: [String: Challenge] = [:]
done

2018-07-18 22:02 UTC, lankastersky commented on zen/models/ChallengesManager.swift
> +                return challengesMap[currentChallengeId]
если ключа нет в словаре то вернется nil что ок потому что возвращаемое значение опциональное

2018-07-18 22:02 UTC, lankastersky commented on zen/models/ChallengesManager.swift
> +        return challengesMap[challengeId]
если ключа нет в словаре то вернется nil что ок потому что возвращаемое значение опциональное

2018-07-18 22:02 UTC, lankastersky commented on zen/models/ChallengesManager.swift
> +        if currentChallengeId == "" {
да, забыл убрать поменял на nil

2018-07-18 22:02 UTC, lankastersky commented on zen/models/ChallengesManager.swift
> +            if !(filteredNonFinishedChallenges.isEmpty) {
не думаю, это вполне законный сценарий, а гарды - когда по идее не должно это условие срабатывать.

2018-07-18 22:02 UTC, lankastersky commented on zen/models/ChallengesManager.swift
> +            if !declinedChallenges.isEmpty
не думаю, это вполне законный сценарий, а гарды - когда по идее не должно это условие срабатывать.

2018-07-18 22:02 UTC, lankastersky commented on zen/views/JournalViewController.swift
> +        let challenge: Challenge = challenges[indexPath.item]
ок добавил assert

2018-07-18 22:56 UTC, merged