UI for challenge workflow
lankastersky/zen-ios pull request #5
Opened 2018-08-03 21:55 UTC by lankastersky

2018-08-04 01:33 UTC, NikAshanin requested changes
https://habr.com/company/touchinstinct/blog/327356/ посмотри здесь, как можно сделать локализацию элегантнее без magic strings в коде

2018-08-04 01:33 UTC, NikAshanin commented on zen/utils/UIView+Utils.swift
> +        guard let view = views[0] as? T else {
views.first

2018-08-04 01:33 UTC, NikAshanin commented on zen/views/challenge_footer_views/FinishedChallengeFooterView.swift
> +    @IBOutlet weak var commentsLabel: UILabel!
private

2018-08-05 03:11 UTC, lankastersky commented on zen/views/challenge_footer_views/FinishedChallengeFooterView.swift
> +    @IBOutlet weak var commentsLabel: UILabel!
done

2018-08-05 03:12 UTC, lankastersky commented on zen/utils/UIView+Utils.swift
> +        guard let view = views[0] as? T else {
done

2018-08-06 20:20 UTC, NikAshanin requested changes

2018-08-06 20:20 UTC, NikAshanin commented on zen/services/FirebaseService.swift
> +                    self.challengesService.storeChallenges(challenges)
weak

2018-08-06 20:20 UTC, NikAshanin commented on zen/services/FirebaseService.swift
> +                    self.storeLastLoadTime()
weak

2018-08-06 20:20 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +        self.view.addGestureRecognizer(tapGesture)
self redundant

2018-08-06 20:20 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +            UITapGestureRecognizer(target: self, action: #selector(self.dismissKeyboard (_:)))
self redundant

2018-08-06 20:20 UTC, NikAshanin commented on zen/views/ChallengeViewController.swift
> +            (self.navigationController?.navigationBar.frame.height ?? 0.0)
self redundant

2018-08-06 20:35 UTC, lankastersky commented on zen/services/FirebaseService.swift
> +                    self.challengesService.storeChallenges(challenges)
if i make it weak, it becomes nil and doesn't work

2018-08-06 20:35 UTC, lankastersky commented on zen/services/FirebaseService.swift
> +                    self.storeLastLoadTime()
if i make it weak, it becomes nil and doesn't work

2018-08-06 20:36 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +        self.view.addGestureRecognizer(tapGesture)
done

2018-08-06 20:36 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +            UITapGestureRecognizer(target: self, action: #selector(self.dismissKeyboard (_:)))
done

2018-08-06 20:36 UTC, lankastersky commented on zen/views/ChallengeViewController.swift
> +            (self.navigationController?.navigationBar.frame.height ?? 0.0)
done

2018-08-08 02:07 UTC, merged